export const events = [
  {
    id: "event-1",
    title: "Kariyer Günleri 2026",
    image: "afis.jpg",
    category: "Seminer",
    date: "12-10-2026",
    time: "14:00",
    location: "A Blok Konferans Salonu",
    description: "Kariyer Günleri 2026 kapsamında farklı sektörlerden önde gelen şirket temsilcileri öğrencilerimizle bir araya gelecektir. Staj olanakları, mülakat ipuçları ve networking seansları düzenlenecektir.",
    capacity: 120,
  },
  {
    id: "event-2",
    title: "Robotik Atölyesi",
    image: "afis2.jpg",
    category: "Atölye",
    date: "20-10-2026",
    time: "10:00",
    location: "Lab 2",
    description: "Robotik ve kodlama dünyasına ilk adımı atın! Bu atölyede katılımcılar temel robotik bileşenlerini, mekanik sistemleri ve programlama mantığını uygulamalı projelerle deneyimleyecek.",
    capacity: 40,
  },
  {
    id: "event-3",
    title: "Siber Güvenlik Söyleşisi",
    image: "event-3.jpg",
    category: "Söyleşi",
    date: "27-10-2026",
    time: "13:00",
    location: "B Blok Amfi 1",
    description: "Sektörden bir uzmanla güvenlik kariyeri üzerine sohbet.",
    capacity: 50,
  },
  {
    id: "event-4",
    title: "Web Tasarım Atölyesi",
    image: "event-4.jpg",
    category: "Atölye",
    date: "03-11-2026",
    time: "15:00",
    location: "Bilgisayar Laboratuvarı 1",
    description: "HTML ve CSS ile ilk kişisel sayfanı yap.",
    capacity: 30,
  },
  {
    id: "event-5",
    title: "Girişimcilik Söyleşisi",
    image: "event-5.jpg",
    category: "Söyleşi",
    date: "10-11-2026",
    time: "13:30",
    location: "B Blok Amfi 2",
    description: "Genç girişimcilerle tanışma ve soru-cevap.",
    capacity: 80,
  },
  {
    id: "event-6",
    title: "Yapay Zeka Semineri",
    image: "event-6.jpg",
    category: "Seminer",
    date: "17-11-2026",
    time: "14:00",
    location: "A Blok Konferans Salonu",
    description: "Yapay zekanın güncel kullanım alanlarına genel bakış.",
    capacity: 100,
  },
];